### ISSUE TITLE
Move the homework to master branch

### ISSUE THREAD

**Issue by Sunnepah** [AHendrix276/ICD0007#1]
Hello @AHendrix276, kindly move the homework solutions to the `master branch` - as it's much easier for us to review. I almost concluded you did only `Animation` task of the `CSS2` homework. I had to change the branch to see the other tasks.

**Comment by AHendrix276** [comment]
Thanks Sunday - apologies for the delay, I just saw this. I believe I merged or at least moved all my lab content to the master branch.

Thanks!
